### PR TITLE
[RHPAM-640] Fix AMQ console route and added route for AMQ tcp service

### PR DESCRIPTION
**Pull request by jakubschwan**
Signed-off-by: Jakub Schwan jschwan@redhat.com

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by errantepiphany** [comment]
@jakubschwan , may I ask the status of this? Is it ready to merge? Because it's still currently marked as a work in progress.

**Comment by spolti** [comment]
Changes looks good, let's wait @jakubschwan status.

**Comment by errantepiphany** [comment]
@jakubschwan This should also be duplicated over to the rhdm template, yes?

**Comment by spolti** [comment]
suppressed by #286

**Pull request closed without merging**
