### PR TITLE
update imagestreams to registry.redhat.io

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@spolti these changes are needed to switch to the new redhat registry. Since openshift/library is pulling from a specific tag you have created in this repo, you'll need to get these changes associated w/ the tag you are using (7.0.0.GA) or update official.yaml in openshift/library to pull from a different branch/tag that has these changes.

**Comment by spolti** [comment]
@bparees these changes can wait for our next sprint to get done?
I think it will happen next week, @errantepiphany is that right?

**Comment by bparees** [comment]
@spolti yes there is no immediate urgency, i'm just trying to get this off my todo list (making sure everyone's imagestreams are updated properly) so the sooner the better from that perspective, but nothing is going to break imminently.

**Comment by spolti** [comment]
@bparees ok, we will target this to the next sprint, I preparing a PR for openshift-ansible to update the templates for the latest version (7.0.2) and for the next release, we will address these changes.
Thanks.

**Comment by spolti** [comment]
targeted to the active sprint: https://issues.jboss.org/browse/RHPAM-1471

**Comment by errantepiphany** [comment]
@bparees @spolti I see this PR is against rhpam70, which is the release branch for 7.0. This should instead go on rhpam70-dev, and we merge to rhpam70 on release. That being said, does this need to go into a forthcoming 7.0 release? Whether or not it is, I think we'll need another PR for the rhpam71-dev branch, toward 7.1.0.GA. Thanks!

**Comment by spolti** [comment]
@errantepiphany good catch, I think we could merge this only on rhpam71-dev  branch.

**Comment by bparees** [comment]
@errantepiphany @spolti I leave it up to you guys to get this into the right branch+tag.  You can cherry-pick this commit and close this PR or whatever you want to do.  But as i noticed in my PR, openshift/library is pulling from the `7.0.0.GA` tag currently.

If you're going to put these changes into rhpam71-dev (and then rhpam71?) then you'll need to update openshift/library to pull from the appropriate branch or tag that you create that includes the changes:

https://github.com/openshift/library/blob/master/official.yaml#L543
https://github.com/openshift/library/blob/master/official.yaml#L9

The important thing is that your imagestreams point to the new registry and set the reference policy to local, and that openshift/library picks up those changes.

**Pull request merged**
