### PR TITLE
[KIECLOUD-97] Synchronize OpenShiftStartupStrategy related changes between Template, APB, and Operator

### PR DESCRIPTION
**Pull request by rhtevan**
a) Remove "KIE_SERVER_USE_SECURE_ROUTE_NAME"
   b) Remove "secure-" prefix from templates and change to base name for https routes
   c) Add "insecure-" prefix http routes

Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [x] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted
- [x] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by rhtevan** [comment]
@errantepiphany @spolti @ricardozanini 
This PR is submitted as per our discussion.

**Comment by sutaakar** [comment]
Seems that the changes are not applied to rhpam74-prod.yaml, is there some reason why that template is not updated? Is it because the template is considered "legacy" and shouldn't be changed?
Also I have noticed that rhpam74-authoring.yaml and rhpam74-authoring-ha.yaml contains still "old" not updated route names.

**Comment by sutaakar** [comment]
One more thing, these changes hint that Kie server location will point to HTTPS route, right? This can bring complications since Business central use Kie server client for runtime operations (tasks, processes). In case of non production usage (when HTTPS certificate will not be valid/will be generated) the Kie server client won't be able to send requests to Kie server, making Business central - Kie server communication failing.

**Comment by ricardozanini** [comment]
@sutaakar this change to use the secure routes instead of non-secure one won't impact the BC and Kieserver communication since they use services via websockets (if not, it should), not routes IIRC. Routes is for cluster external access only.

About the `rhpam74-authoring-ha.yaml` and `rhpam74-authoring.yaml` I think @rhtevan might have forgotten to change the routes names.

About the `rhpam74-prod.yaml`, it should be updated IMO.

**Comment by sutaakar** [comment]
@ricardozanini Related to BC - Kie server communication, there are actually 2 "channels". First is BC controller capability, this one is handled by WebSockets for 7.3, will be replaced by OpenShiftStartupStrategy. The second one is starting/managing processes and tasks from BC, for this a Kie server client is used, communicating with Kie server using REST endpoints.

**Comment by errantepiphany** [comment]
> @ricardozanini Related to BC - Kie server communication, there are actually 2 "channels". First is BC controller capability, this one is handled by WebSockets for 7.3, will be replaced by OpenShiftStartupStrategy. The second one is starting/managing processes and tasks from BC, for this a Kie server client is used, communicating with Kie server using REST endpoints.

@sutaakar @ricardozanini  Regarding starting/managing processes and tasks from BC, are you saying it can't handle httpS? When we say secure route, we just mean it uses tls, not that it requires authentication. If it really can't handle tls, then maybe we can just change the org.kie.server.location property to default to the "insecure-" prefix?

**Comment by ricardozanini** [comment]
> @ricardozanini Related to BC - Kie server communication, there are actually 2 "channels". First is BC controller capability, this one is handled by WebSockets for 7.3, will be replaced by OpenShiftStartupStrategy. The second one is starting/managing processes and tasks from BC, for this a Kie server client is used, communicating with Kie server using REST endpoints.

Acked, but the REST endpoints should be reached using services, not routes. If it's using routes is wrong, IMO. Routes is meant to be used only to external access, not intra-cluster communications. Since BC and Kieserver is deployed in the same cluster, same namespace, they should rely on services. Using routes means that the request will pass through the OpenShift HAProxy, which is a useless roundtrip to reach the BC/Kieserver pod.

**Comment by errantepiphany** [comment]
> > @ricardozanini Related to BC - Kie server communication, there are actually 2 "channels". First is BC controller capability, this one is handled by WebSockets for 7.3, will be replaced by OpenShiftStartupStrategy. The second one is starting/managing processes and tasks from BC, for this a Kie server client is used, communicating with Kie server using REST endpoints.
> 
> @sutaakar @ricardozanini Regarding starting/managing processes and tasks from BC, are you saying it can't handle httpS? When we say secure route, we just mean it uses tls, not that it requires authentication. If it really can't handle tls, then maybe we can just change the org.kie.server.location property to default to the "insecure-" prefix?

Just looked at the prod template. We set the HOSTNAME_HTTP and HOSTNAME_HTTPS parameters to KIE_SERVER1_HOSTNAME_HTTPS and KIE_SERVER1_HOSTNAME_HTTPS, respectively. If we DON'T set the KIE_SERVER_ROUTE_NAME (remove it) then the org.kie.server.location property will create a simple url based on KIE_SESRVER1_HOSTNAME_HTTP. (We can also ensure this by setting the KIE_SERVER_PROTOCOL to "http". We actually wouldn't need to set the HOSTNAME_HTTPS param, either. Am I missing something, or would that work?

**Comment by errantepiphany** [comment]
> EDIT: @errantepiphany @rhtevan @sutaakar you guys that have more experience with the product than I, the `org.kie.server.location` is meant to be used for the REST endpoints communication between BC and Kieserver? If it's, I think we should drop the use of routes in this context. Should use services. Is there a reason for that? If so, @sutaakar has a point: the client could end up having problems with a scenario with self-signed certificates, unless we add the secret as truststore in both ends (I think we do)

@ricardozanini The value of org.kie.server.location also shows up in the BC user interface as a clickable link when looking at the execution servers, thus the Route is the only way to fulfill both purposes. I _thought_ I heard that there was a way to hide this link in BC, but I can't remember. @spolti , @rhtevan ?

**Comment by ricardozanini** [comment]
> We actually wouldn't need to set the HOSTNAME_HTTPS param, either. Am I missing something, or would that work?

I think we need, because this will be used together with KIE_SERVER_PROTOCOL to create a default secure URL if no KIE_SERVER_ROUTE_NAME is passed:

https://github.com/jboss-container-images/jboss-kie-modules/pull/259/files#diff-45a838030c9b80a321a090d01f4ea75aL400

**Comment by ricardozanini** [comment]
> @ricardozanini The value of org.kie.server.location also shows up in the BC user interface as a clickable link when looking at the execution servers, thus the Route is the only way to fulfill both purposes. I thought I heard that there was a way to hide this link in BC, but I can't remember. @spolti , @rhtevan ?

Regarding the user interface, I guess we could have another property to expose it. But between the pods, the communication should be done via services.

I'm also having this same problem with the git http feature: I wish to disable the dropdown box with the HTTP information and only enable the HTTPS one, but it's impossible since if I disable the HTTP property, the git http feature doesn't work at all.

**Comment by errantepiphany** [comment]
> Regarding the user interface, I guess we could have another property to expose it. But between the pods, the communication should be done via services.

I've made this argument before (the need for a separate property), but we still don't have one. For 7.4, we are still stuck with just the one.

**Comment by spolti** [comment]
> but I can't remember. @spolti , @rhtevan ?

It automatilly hidden when any of the provided url is accessible. I Don't remember if there is a way to explicit hide that.

**Comment by ricardozanini** [comment]
> I've made this argument before (the need for a separate property), but we still don't have one. For 7.4, we are still stuck with just the one.

No problem, but I think we should have a JIRA to track this, wdyt? Changing the endpoint REST communications to services instead of routes. 

Regarding the @sutaakar concern, I think we need to test more this integration. Besides that, this is the way the Operators and APB is working today. I'll run some tests today though.

I haven't found any clue about a truststore being added to the kieserver nor the BC. I think we should have the pub cert from each other on its truststore.

**Pull request merged**
