### PR TITLE
[RHBA-647] - Missing SSO and jboss-maven modules for Standalone contr…

### PR DESCRIPTION
**Pull request by spolti**
…oller image

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by bmozaffa** [comment]
@spolti I haven't dug in to see why this broke, but can it be fixed by excluding something, versus including a dependency? We should only need SSO for business-central.

**Comment by sutaakar** [comment]
I think that SSO (Keycloak) should be configured for Standalone controller too so it can integrate with SSO server.
@spolti Why is there needed jboss-maven module? Is it related to SSO? Otherwise Standalone controller doesn't need any Maven service.

**Comment by bmozaffa** [comment]
@sutaakar Karen, would you please elaborate on what it means for the controller to integrate with SSO?

**Comment by spolti** [comment]
@sutaakar THe maven module is needed by bpmsuite-common.sh:
/opt/eap/bin/launch/bpmsuite-common.sh: line 4: /usr/local/s2i/scl-enable-maven: No such file or directory

**Comment by sutaakar** [comment]
@bmozaffa I meant that the authentication and authorization of users connecting to the standalone controller is served by external SSO server.

**Comment by bmozaffa** [comment]
@sutaakar I don't believe end users authenticate against the controller at all.

**Comment by sutaakar** [comment]
@bmozaffa Who should access and authenticate against the controller then?

**Comment by bmozaffa** [comment]
@sutaakar The KIE server does, and it would be hardcoded with the controller's credentials.

**Comment by bmozaffa** [comment]
@sutaakar We haven't validated using the controller without business central. Even when set up standalone, my working assumption has been that configuration would happen from business central connecting to it. This may be a valid use case, but I'd like to demand for it before investing any time in creating templates and validating the setup, much less providing SSO.

**Pull request closed without merging**
