### PR TITLE
[RHPAM-2576] Set package manager

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

Fiix https://issues.redhat.com/browse/RHPAM-2576

### CODE REVIEW

**Comment by ruromero** [comment]
@spolti do you mind reviewing again? Thanks

**Comment by ruromero** [comment]
@spolti I have updated the base image and the build worked without issues. The links to the drivers look also fine and are discovered by the application when configured

**Comment by spolti** [comment]
Awesome, thanks.

**Comment by spolti** [comment]
Hi @errantepiphany , do you know if the image name is something required by prod that we need to keep like ubi8-minimal:8released or can we use the full image name?

**Comment by errantepiphany** [comment]
> Hi @errantepiphany , do you know if the image name is something required by prod that we need to keep like ubi8-minimal:8released or can we use the full image name?

@spolti , @ruromero : I don't know... I just sent an email to the Prod team to ask them, and cc'd you both.

**Comment by spolti** [comment]
@ruromero can you please rebase?

**Comment by ruromero** [comment]
@spolti done

**Pull request merged**
