### PR TITLE
Fix authoring ha RHPAMCENTR user place in deployment config

### PR DESCRIPTION
**Pull request by jakubschwan**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by jakubschwan** [comment]
@ruromero please take a look as well

**Comment by spolti** [comment]
Shouldn't kieserser and business central have the credentials?

**Comment by jakubschwan** [comment]
This credential should be for Kie Server only, for Business Central is right now only use user from the secret. This user was placed to wrong Deployment. In Authoring template it is configured correctly.

**Comment by spolti** [comment]
@jakubschwan Thanks for fixing this :)

**Pull request merged**
