### PR TITLE
[RHPAM-1643] - Deprecate rhpam72-sit application template and make th…

### PR DESCRIPTION
**Pull request by spolti**
…e pod replicas configurable on rhpam72-prod template

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by errantepiphany** [comment]
@spolti I just commented on the jira, that I don't think we need to keep the deprecated template around, as long as we document this in the release notes. Customers will simply need to use the other template, as the parameters they are depending on haven't changed. Please note this PR is "on hold" until we get acks.

**Comment by spolti** [comment]
Template is deleted.

**Comment by spolti** [comment]
Template is deleted.

**Comment by errantepiphany** [comment]
@spolti Approved now that the rhpam72-sit.yaml template has been deleted. Still "on hold" until we have full acks on the jira. I want to make sure that QE approves, which probably means they will have to update their tests.

**Pull request merged**
