### PR TITLE
[RHPAM-2175] Add variable to image.yaml file

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

Fix https://issues.jboss.org/browse/RHPAM-2175

Follow up PR for https://github.com/jboss-container-images/jboss-kie-modules/pull/334

### CODE REVIEW

**Comment by ruromero** [comment]
@spolti please review

**Comment by ruromero** [comment]
Depends on #410 
Rebase and keep only EXTERNAL_AUTH_ONLY changes

**Comment by spolti** [comment]
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/410 mergede, Ruben can you please rebase?

**Comment by ruromero** [comment]
@spolti rebased, please review again

**Pull request merged**
