### PR TITLE
[RHPAM-1850] Correct KIE_SERVER_CONTROLLER_PROTOCOL value for Smart r…

### PR DESCRIPTION
**Pull request by sutaakar**
…outer

https://issues.jboss.org/browse/RHPAM-1850

Signed-off-by: Karel Suta <ksuta@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by sutaakar** [comment]
@errantepiphany Please take a look.

**Comment by errantepiphany** [comment]
@sutaakar So, it looks like the rhpam73-prod.yaml template uses "http" for smartrouter/controller communication, but rhpam73-prod-immutable-monitor.yaml uses "ws". I'm assuming this PR is to make them both the same? I'm curious why "http" for smartrouter/controller communication whereas we use "ws" for kieserver/controller communication. Does is not work otherwise?

**Comment by spolti** [comment]
I had the same question, did we decide to use http insteado ws?

**Comment by sutaakar** [comment]
Smart router connects to the controller using http requests:
https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java#L253
It cannot handle WebSocket communication.

**Comment by errantepiphany** [comment]
@sutaakar Awesome, thanks.

**Pull request merged**
