### PR TITLE
[CLOUD-2692] move material out to modules

### PR DESCRIPTION
**Pull request by jmtd**
move some stuff from image.yaml out to modules in cct_module

https://issues.jboss.org/browse/CLOUD-2413

### CODE REVIEW

**Comment by spolti** [comment]
@jmtd can you please rebase?

**Comment by jmtd** [comment]
> @jmtd can you please rebase?

I've just re-created the commits on top of -dev and force-pushed.

**Comment by spolti** [comment]
@jmtd Thanks.
@errantepiphany f.y.i.

**Comment by errantepiphany** [comment]
Closing this PR in favor of more complete changes here: https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/122

**Pull request closed without merging**
