### PR TITLE
[RHPAM-1210] - Allow LDAP authentication in RHPAM

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

Fix https://issues.jboss.org/browse/RHPAM-1210
Added LDAP attributes to templates

### CODE REVIEW

**Comment by ruromero** [comment]
@errantepiphany please review. Note that I haven't use the same name for the variables for the parameters for readability

**Comment by spolti** [comment]
Why not use LDAP_AUTH_** for everything instead KIE_AUTH_LDAP?

**Comment by ruromero** [comment]
@spolti @errantepiphany
Given the latest discussions and the intention to move the scripts to the cct_modules I'll rename all to just LDAP_*

**Comment by jakubschwan** [comment]
From my point of view, it does not make sense to combine SSO and LDAP variables in one template. I think it would be better to have only one configuration in template (SSO and maybe one template with LDAP) and well documented configuration of LDAP.

**Comment by ruromero** [comment]
@spolti @errantepiphany Renaming done

**Comment by errantepiphany** [comment]
@jakubschwan We are moving forward with including this in the templates for now, however will revisit it before finalization of 7.0.2.GA. It will be easy to remove the variables from the templates if that's what gets decided. @ruromero, @spolti  , FYI.

**Pull request merged**
