### PR TITLE
[RHPAM-3245] - Change resource requirements for BC and KIE Server

### PR DESCRIPTION
**Pull request by Kaitou786**
See: https://issues.redhat.com/browse/RHPAM-3245

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [x] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted
- [x] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by msmagnanijr — APPROVED** [review]
lgtm

**Comment by Kaitou786** [comment]
@spolti I changed the name on other places from `KIE server` -> `KIE Server`. I hope that's okay but let me know if you want me to revert

**Review by spolti — APPROVED** [review]
Thanks @Kaitou786 looks good.
do you mind to cherry pick on 7.9.x branch?

**Comment by Kaitou786** [comment]
@spolti [cherrypick](https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/479)

**Comment by mramendi** [comment]
> @mramendi do you mind to take a look?

LGTM. There are some new settings to doc, so if you could tell me in what version they are coming in, it would be great.

**Review by mramendi — APPROVED** [review]

**Comment by spolti** [comment]
@mramendi what settings are you referring to?

**Comment by mramendi** [comment]
@spolti I am referring to BUSINESS_CENTRAL_MEMORY_LIMIT, BUSINESS_CENTRAL_CPU_REQUEST, KIE_SERVER_MEMORY_REQUEST .

The 7.8 doc for this subject matter in templates is https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.8/html/deploying_a_red_hat_process_automation_manager_authoring_environment_on_red_hat_openshift_container_platform/environment-authoring-con#template-deploy-ha-resources-authoring-proc and the 7.9 doc will not have any material change there. I would really appreciate it if you could tell me at which point (7.9GA? 7.9.1? 7.10?) the changes come in - and also if they are going to show up in Operator as well.

**Comment by spolti** [comment]
I see, sry.
THis change is for 7.9.1.

**Pull request merged**
