### PR TITLE
[RHPAM-1076] Added RH-SSO to KIEServers

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

Fixes https://issues.jboss.org/browse/RHPAM-1076

Added SSO parameters to KIE Servers where Business Central or Business Central Monitoring can configure it

### CODE REVIEW

**Comment by ruromero** [comment]
Please review @errantepiphany @spolti

**Comment by ruromero** [comment]
@jakubschwan I used the same values across all the templates. Did I miss one?
There are 3 types of variables:
* Common variables SSO_*
* Business Central variables BUSINESS_CENTRAL_SSO_*
* KIE Server variables KIE_SERVER_X_SSO_*

Do you mean use SSO_ prefix for all?
Thanks

**Comment by ruromero** [comment]
I confirmed values are properly set in each DC for each template I updated

**Comment by errantepiphany** [comment]
@ruromero And confirmed the errors went away? Also, I think @jakubschwan was just talking about the **display** name and description, not the actual parameter names.

**Comment by ruromero** [comment]
@errantepiphany only with the authoring template but as the params are the same I don’t see why it wouldn’t work

**Comment by errantepiphany** [comment]
@ruromero Okay I'll merge the PR and let QE test. Thanks!

**Pull request merged**
